dist: trusty
sudo: false

language: go
go: [ "1.11" ]
env:
  global:
  - PATH=$PATH:$HOME/gopath/bin
  - GO111MODULE=on

before_install:
- echo "machine github.com login $BUNDLE_GITHUB__COM" > $HOME/.netrc
- echo "machine raw.githubusercontent.com login $BUNDLE_GITHUB__COM" >> $HOME/.netrc
- chmod 600 $HOME/.netrc

install:
- go mod tidy

script:
- go test ./...
